apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back
  name: back
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - image: rdegtyarev/netology-hw-13.01-back
          imagePullPolicy: IfNotPresent
          name: back
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres.default:5432/news"
---
apiVersion: v1
kind: Service
metadata:
  name: back
  namespace: prod
spec:
  ports:
    - name: back
      port: 9000
  selector:
    app: back
  type: ClusterIP