apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: front
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - image: rdegtyarev/netology-hw-13.01-front:latest
          imagePullPolicy: IfNotPresent
          name: front
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod-front-srv
  namespace: prod
spec:
  ports:
    - name: front
      port: 8080
      targetPort: 80
  selector:
    app: front
  type: ClusterIP
